# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0008_auto_20170601_1822'),
        ('wl_main', '0040_auto_20250204_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceClone'),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='licence_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceTypeClone'),
        ),
    ]
