# Generated by Django 3.2.25 on 2025-02-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0008_auto_20170601_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrow',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='data_descriptor',
            field=models.JSONField(),
        ),
    ]
