# Generated by Django 3.2.25 on 2025-02-14 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_returns', '0009_auto_20250214_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='proxy_customer_id',
            new_name='proxy_customer',
        ),
        migrations.AlterField(
            model_name='return',
            name='proxy_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='returnamendmentrequest',
            old_name='officer_id',
            new_name='officer',
        ),        
        migrations.AlterField(
            model_name='returnamendmentrequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
