# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0009_auto_20250204_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='licence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='licence_type',
            field=models.IntegerField(),
        ),
    ]
