# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0010_auto_20250204_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicence'),
        ),
        migrations.AlterField(
            model_name='returntype',
            name='licence_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceType'),
        ),
    ]
