# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_returns', '0011_auto_20250204_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='proxy_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnamendmentrequest',
            name='officer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
