# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-10 07:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db.models import ForeignKey


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0026_auto_20250210_1538'),
        ('wl_applications', '0018_auto_20170612_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='hard_copy_id',
            new_name='hard_copy',
        ),
        migrations.AlterField(
            model_name='application',
            name='hard_copy',
            field=ForeignKey(blank=True, null=True,  
                  on_delete=django.db.models.deletion.CASCADE,
                    related_name='hard_copy',
                    to='wl_main.Document'),
        ),
    ]
