# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0019_auto_20250204_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='licence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='licence_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
