# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-11 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0026_auto_20250210_1538'),
        ('wl_applications', '0019_application_documents'),
    ]

    operations = [
        migrations.AddField(    
            model_name='application',
            name='documents',
            field=models.ManyToManyField(to='wl_main.Document'),
        ),    
    ]
