# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0020_auto_20250204_1223'),
        ('wl_main', '0045_auto_20250204_1549')
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicence'),
        ),
        migrations.AlterField(
            model_name='application',
            name='licence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceType'),
        ),
    ]
