# Generated by Django 3.2.25 on 2025-02-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0020_application_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
