# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0051_auto_20250205_1050'),
        ('wl_applications', '0021_auto_20250204_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_documents',
            field=models.ManyToManyField(to='wl_main.LocalDocument'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hard_copy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
