# Generated by Django 3.2.25 on 2025-02-14 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0035_auto_20250214_1158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_applications', '0021_alter_application_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applicant_profile_id',
            new_name='applicant_profile',
        ),        
        migrations.AlterField(
            model_name='application',
            name='applicant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wl_main.profile'),
        ),
        migrations.RenameField(
            model_name='applicationdeclineddetails',
            old_name='officer_id',
            new_name='officer',
        ),             
        migrations.AlterField(
            model_name='applicationdeclineddetails',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='applicationrequest',
            old_name='officer_id',
            new_name='officer',
        ),               
        migrations.AlterField(
            model_name='applicationrequest',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='assigned_assessor_id',
            new_name='assigned_assessor',
        ),            
        migrations.AlterField(
            model_name='assessment',
            name='assigned_assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
