# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0022_auto_20250205_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hard_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hard_copy', to='wl_main.LocalDocument'),
        ),
    ]
