# Generated by Django 3.2.25 on 2025-02-14 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_applications', '0022_auto_20250214_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='proxy_applicant_id',
            new_name='proxy_applicant',
        ),
        migrations.AlterField(
            model_name='application',
            name='proxy_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy', to=settings.AUTH_USER_MODEL),
        ),
    ]
