# Generated by Django 3.2.25 on 2025-02-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_applications', '0023_alter_application_proxy_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='assigned_officer_id',
            new_name='assigned_officer',
        ),
        migrations.AlterField(
            model_name='application',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
