# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 03:34
from __future__ import unicode_literals

from django.db import migrations

def copy_m2m_document_to_local_document(apps, schema_editor):
    Application = apps.get_model('wl_applications', 'Application')
    LocalDocument = apps.get_model('wl_main', 'LocalDocument')
    for application in Application.objects.all():
        for document in application.documents.all():   
            local_document = LocalDocument.objects.get(pk=document.pk)
            application.application_documents.add(local_document)

class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0023_auto_20250205_1053'),
    ]

    operations = [
        migrations.RunPython(copy_m2m_document_to_local_document),
    ]
