# Generated by Django 5.0.12 on 2025-02-26 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wl_applications", "0024_alter_application_assigned_officer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationuseraction",
            old_name="who_id",
            new_name="who",
        ),
        migrations.AlterField(
            model_name="applicationuseraction",
            name="who",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
