# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0024_auto_20250205_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
    ]
