# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0025_remove_application_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_documents',
            new_name='documents',
        ),
    ]
