# Generated by Django 5.0.13 on 2025-03-12 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wl_applications", "0025_alter_applicationuseraction_who"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="payment_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
