# Generated by Django 5.0.13 on 2025-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_applications', '0026_application_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
