# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-10 06:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0025_wildlifelicencetype_default_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='%Y/%m/%d')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('holder', models.IntegerField()),
                ('issuer', models.IntegerField(blank=True, null=True)),
                ('licence_number', models.CharField(blank=True, max_length=64, null=True)),
                ('licence_sequence', models.IntegerField(blank=True, default=0)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_renewable', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(blank=True, help_text='The display name that will show in the dashboard', max_length=30, null=True)),
                ('version', models.SmallIntegerField(default=1)),
                ('code', models.CharField(max_length=64)),
                ('act', models.CharField(blank=True, max_length=256)),
                ('statement', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, max_length=64)),
                ('is_renewable', models.BooleanField(default=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wl_main.LicenceType')),
            ],
        ),
        migrations.AddField(
            model_name='licence',
            name='licence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wl_main.LicenceType'),
        ),
        migrations.AlterUniqueTogether(
            name='licencetype',
            unique_together=set([('short_name', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='licence',
            unique_together=set([('licence_number', 'licence_sequence')]),
        ),
    ]
