# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-04 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0025_wildlifelicencetype_default_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomosTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'NOMOS Taxonomies',
            },
        ),
    ]
