# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0026_nomostaxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomostaxonomy',
            name='taxon_name_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nomostaxonomy',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
