# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-11 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0027_auto_20250211_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='holder',
            new_name='holder_id',
        ),
        migrations.RenameField(
            model_name='licence',
            old_name='issuer',
            new_name='issuer_id',
        ),
    ]
