# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-11 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0028_auto_20250211_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildlifelicence',
            old_name='licence_ptr_id',
            new_name='licence_ptr',
        ),
        migrations.RenameField(
            model_name='wildlifelicencetype',
            old_name='licencetype_ptr_id',
            new_name='licencetype_ptr',
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='licence_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wl_main.Licence'),
        ),
        migrations.AlterField(
            model_name='wildlifelicencetype',
            name='licencetype_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wl_main.LicenceType'),
        ),
    ]
