# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0028_auto_20250203_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseLicenceType',
            new_name='LicenceType',
        ),
    ]
