# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0029_auto_20250211_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationslogentry',
            name='documents',
            field=models.ManyToManyField(blank=True, to='wl_main.Document'),
        ),
    ]
