# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0029_auto_20250203_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseLicence',
            new_name='Licence',
        ),
    ]
