# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0030_auto_20250203_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licence',
            new_name='BaseLicence',
        ),
        migrations.RenameModel(
            old_name='LicenceType',
            new_name='BaseLicenceType',
        ),
    ]
