# Generated by Django 3.2.25 on 2025-02-14 01:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_main', '0030_communicationslogentry_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='is_renewable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licencetype',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='extracted_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wl_main.wildlifelicence'),
        ),
        migrations.AlterField(
            model_name='wildlifelicencetype',
            name='application_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicencetype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wl_main.wildlifelicencecategory'),
        ),
    ]
