# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models

def populate_licencetype_ptr(apps, schema_editor):
    WildlifeLicenceType = apps.get_model('wl_main', 'WildlifeLicenceType')
    for licence_type in WildlifeLicenceType.objects.all():
        licence_type.licencetype_ptr_store = licence_type.licencetype_ptr_id
        licence_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0031_auto_20250203_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselicencetype',
            name='licencetype_ptr_store',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_licencetype_ptr),
    ]
