# Generated by Django 3.2.25 on 2025-02-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0032_auto_20250214_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user_id', 'hash')},
        ),
    ]
