# Generated by Django 3.2.25 on 2025-02-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0033_auto_20250214_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
