# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 05:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0033_auto_20250203_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceTypeClone',
            fields=[
                ('baselicencetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wl_main.BaseLicenceType')),
                ('product_title', models.CharField(max_length=64, unique=True)),
                ('identification_required', models.BooleanField(default=False)),
                ('senior_applicable', models.BooleanField(default=False)),
                ('default_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Default Licence Period (days)')),
                ('application_schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True)),
                ('licencetype_ptr_store', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceCategory')),
                ('default_conditions', models.ManyToManyField(blank=True, through='wl_main.DefaultCondition', to='wl_main.Condition')),
                ('variant_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.VariantGroup')),
            ],
            options={
                'abstract': False,
            },
            bases=('wl_main.baselicencetype',),
        ),
        migrations.AddField(
            model_name='defaultcondition',
            name='wildlife_licence_type_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceTypeClone'),
        ),
    ]
