# Generated by Django 3.2.25 on 2025-02-14 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_main', '0034_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='oscar_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wl_profile_addresses', to='wl_main.useraddress'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wl_profile_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='communicationslogentry',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
