# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 06:19
from __future__ import unicode_literals

from django.db import migrations

def copy_licence_types_to_clone(apps, schema_editor):
    WildlifeLicenceType = apps.get_model('wl_main', 'WildlifeLicenceType')
    WildlifeLicenceTypeClone = apps.get_model('wl_main', 'WildlifeLicenceTypeClone')
    DefaultCondition = apps.get_model('wl_main', 'DefaultCondition')

    for licence_type in WildlifeLicenceType.objects.all():
        wltc = WildlifeLicenceTypeClone(
            pk=licence_type.pk,
            product_title=licence_type.product_title,
            identification_required=licence_type.identification_required,
            senior_applicable=licence_type.senior_applicable,
            default_period=licence_type.default_period,
            application_schema=licence_type.application_schema,
            category=licence_type.category,
            variant_group=licence_type.variant_group,
            help_text=licence_type.help_text,
            baselicencetype_ptr_id=licence_type.licencetype_ptr_id,
        )
        wltc.save()

        # add the default conditions
        order = 1
        for condition in licence_type.default_conditions.all():
            dc = DefaultCondition(
                condition=condition,
                wildlife_licence_type_clone=wltc,
                order=order,
            )
            dc.save()
            order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0035_auto_20250203_1419'),
    ]

    operations = [
        migrations.RunPython(copy_licence_types_to_clone),
    ]

