# Generated by Django 3.2.25 on 2025-02-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0035_auto_20250214_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
