# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-03 06:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20250203_1006'),
        ('wl_main', '0036_auto_20250203_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeLicenceClone',
            fields=[
                ('baselicence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wl_main.BaseLicence')),
                ('purpose', models.TextField(blank=True)),
                ('locations', models.TextField(blank=True)),
                ('cover_letter_message', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('return_frequency', models.IntegerField(choices=[(-1, 'One off'), (1, 'Monthly'), (3, 'Quarterly'), (6, 'Twice-Yearly'), (12, 'Yearly')], default=-1)),
                ('renewal_sent', models.BooleanField(default=False)),
                ('extracted_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cover_letter_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clone_cover_letter_document', to='accounts.Document')),
                ('licence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clone_licence_document', to='accounts.Document')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('regions', models.ManyToManyField(to='wl_main.Region')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceClone')),
                ('variants', models.ManyToManyField(blank=True, through='wl_main.WildlifeLicenceVariantLink', to='wl_main.Variant')),
            ],
            options={
                'abstract': False,
            },
            bases=('wl_main.baselicence',),
        ),
        migrations.RemoveField(
            model_name='defaultcondition',
            name='wildlife_licence_type_clone',
        ),
        migrations.RemoveField(
            model_name='wildlifelicencetype',
            name='default_conditions',
        ),
        migrations.AlterField(
            model_name='defaultcondition',
            name='wildlife_licence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceTypeClone'),
        ),
        migrations.AddField(
            model_name='wildlifelicencevariantlink',
            name='licence_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceClone'),
        ),
    ]
