# Generated by Django 3.2.25 on 2025-02-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0036_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
