# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0037_auto_20250203_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicencevariantlink',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicence'),
        ),
    ]
