# Generated by Django 3.2.25 on 2025-02-14 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_main', '0037_rename_user_id_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationslogentry',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
