# Generated by Django 3.2.25 on 2025-02-17 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wl_main', '0038_auto_20250214_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessorgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
