# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 02:01
from __future__ import unicode_literals

from django.db import migrations


def copy_licences_to_clone(apps, schema_editor):
    WildlifeLicence = apps.get_model('wl_main', 'WildlifeLicence')
    WildlifeLicenceClone = apps.get_model('wl_main', 'WildlifeLicenceClone')
    WildlifeLicenceVariantLink = apps.get_model('wl_main', 'WildlifeLicenceVariantLink')
    BaseLicence = apps.get_model('wl_main', 'BaseLicence')

    for licence in WildlifeLicence.objects.all().order_by('id'):
        base_licence = BaseLicence.objects.get(pk=licence.licence_ptr_id)
        wlc = WildlifeLicenceClone(
            pk=licence.pk,
            profile=licence.profile,
            purpose=licence.purpose,
            locations=licence.locations,
            cover_letter_message=licence.cover_letter_message,
            additional_information=licence.additional_information,
            licence_document=licence.licence_document,
            cover_letter_document=licence.cover_letter_document,
            return_frequency=licence.return_frequency,
            renewal_sent=licence.renewal_sent,
            extracted_fields=licence.extracted_fields,
            baselicence_ptr=base_licence,
        )
        wlc.save_base(raw=True)

        # add regions
        for region in licence.regions.all():
            wlc.regions.add(region)

        # add the variants
        order = 1
        for variant in licence.variants.all():
            dc = WildlifeLicenceVariantLink(
                variant=variant,
                licence_clone=wlc,
                order=order,
            )
            dc.save()
            order += 1

class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0038_auto_20250204_1001'),
    ]

    operations = [
        migrations.RunPython(copy_licences_to_clone),
    ]
