# Generated by Django 5.0.12 on 2025-02-19 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wl_main", "0039_auto_20250217_0924"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="licence",
            old_name="holder_id",
            new_name="holder",
        ),
        migrations.RenameField(
            model_name="licence",
            old_name="issuer_id",
            new_name="issuer",
        ),
        migrations.RenameField(
            model_name="wildlifelicence",
            old_name="cover_letter_document_id",
            new_name="cover_letter_document",
        ),
        migrations.RenameField(
            model_name="wildlifelicence",
            old_name="licence_document_id",
            new_name="licence_document",
        ),
        migrations.RenameField(
            model_name="wildlifelicence",
            old_name="profile_id",
            new_name="profile",
        ),
        migrations.AlterField(
            model_name="licence",
            name="holder",
            field=models.ForeignKey(
                default=1,  # Allow rows should already have data so this is just to keep django happy
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holder",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="licence",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issuer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wildlifelicence",
            name="cover_letter_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cover_letter_document",
                to="wl_main.document",
            ),
        ),
        migrations.AlterField(
            model_name="wildlifelicence",
            name="licence_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licence_document",
                to="wl_main.document",
            ),
        ),
        migrations.AlterField(
            model_name="wildlifelicence",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="wl_main.profile"
            ),
        ),
    ]
