# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 02:10
from __future__ import unicode_literals

from django.db import migrations


def populate_licence_clone_replaced_by(apps, schema_editor):
    WildlifeLicenceClone = apps.get_model('wl_main', 'WildlifeLicenceClone')
    WildlifeLicence = apps.get_model('wl_main', 'WildlifeLicence')

    for licence_clone in WildlifeLicenceClone.objects.all():
        licence = WildlifeLicence.objects.get(id=licence_clone.pk)
        if not licence.replaced_by_id:
            continue

        replaced_by_license = WildlifeLicenceClone.objects.get(id=licence.replaced_by_id)
        licence_clone.replaced_by = replaced_by_license
        licence_clone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0039_auto_20250204_1001'),
    ]

    operations = [
        migrations.RunPython(populate_licence_clone_replaced_by),
    ]
