# Generated by Django 5.0.12 on 2025-02-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0040_remove_licence_holder_id_remove_licence_issuer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wl_main_assessorgroup_members',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
