# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0040_auto_20250204_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='variants',
        ),
        migrations.RemoveField(
            model_name='wildlifelicencevariantlink',
            name='licence',
        ),
    ]
