# Generated by Django 5.0.12 on 2025-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0041_assessorgroupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessorGroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wl_main_assessorgroup_members',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='assessorgroupmember',
            options={},
        ),
    ]
