# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_auto_20160802_0859'),
        ('wl_main', '0041_auto_20250204_1126'),
        ('wl_returns', '0009_auto_20250204_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='cover_letter_document',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='licence_document',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='licence_ptr',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='wildlifelicence',
            name='replaced_by',
        ),
        migrations.RemoveField(
            model_name='wildlifelicencetype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wildlifelicencetype',
            name='licencetype_ptr',
        ),
        migrations.RemoveField(
            model_name='wildlifelicencetype',
            name='variant_group',
        ),
        migrations.DeleteModel(
            name='WildlifeLicence',
        ),
        migrations.DeleteModel(
            name='WildlifeLicenceType',
        ),
    ]
