# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0042_auto_20250204_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicenceclone',
            name='variants',
        ),
        migrations.RemoveField(
            model_name='wildlifelicencetypeclone',
            name='default_conditions',
        ),
        migrations.AlterField(
            model_name='defaultcondition',
            name='wildlife_licence_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicencevariantlink',
            name='licence_clone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
