# Generated by Django 5.0.12 on 2025-02-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0042_assessorgroupmembers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessorGroupMember',
        ),
    ]
