# Generated by Django 5.0.12 on 2025-02-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0043_delete_assessorgroupmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessorgroupmembers',
            options={},
        ),
    ]
