# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0043_auto_20250204_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcondition',
            name='wildlife_licence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceTypeClone'),
        ),
        migrations.AlterField(
            model_name='wildlifelicencevariantlink',
            name='licence_clone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wl_main.WildlifeLicenceClone'),
        ),
    ]
