# Generated by Django 5.0.13 on 2025-03-11 02:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wl_main", "0044_alter_assessorgroupmembers_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildlifelicencetype",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
    ]
