# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0044_auto_20250204_1547'),
        ('wl_returns', '0010_auto_20250204_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WildlifeLicenceClone',
            new_name='WildlifeLicence',
        ),
        migrations.RenameModel(
            old_name='WildlifeLicenceTypeClone',
            new_name='WildlifeLicenceType',
        ),
    ]
