# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0046_auto_20250204_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicence',
            name='variants',
            field=models.ManyToManyField(blank=True, through='wl_main.WildlifeLicenceVariantLink', to='wl_main.Variant'),
        ),
    ]
