# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0047_wildlifelicence_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlifelicencetype',
            name='default_conditions',
            field=models.ManyToManyField(blank=True, through='wl_main.DefaultCondition', to='wl_main.Condition'),
        ),
    ]
