# Generated by Django 5.0.13 on 2025-03-12 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0047_rename_name_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discountable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='oracle_code',
            field=models.CharField(default='WILDLIFE_LICENSING_DEFAULT_ORACLE_CODE', max_length=50),
        ),
    ]
