# Generated by Django 5.0.13 on 2025-03-18 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wl_main", "0048_assessorgroupmembers_assessorgroup_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_discountable",
            field=models.BooleanField(
                default=True,
                help_text="This flag indicates if this product can be used in an offer or not",
                verbose_name="Is discountable?",
            ),
        ),
    ]
