# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-04 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0048_wildlifelicencetype_default_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlifelicencetype',
            name='licencetype_ptr_store',
        ),
    ]
