# Generated by Django 5.0.13 on 2025-03-18 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0049_assessorgroupmembers_assessorgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_discountable',
            field=models.BooleanField(default=True, help_text='This flag indicates if the user can have a seniors discount on this product', verbose_name='Is discountable?'),
        ),
    ]
