# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0050_localdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationslogentry',
            name='comms_log_documents',
            field=models.ManyToManyField(blank=True, to='wl_main.LocalDocument'),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='cover_letter_document',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='licence_document',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
