# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0051_auto_20250205_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildlifelicence',
            name='cover_letter_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_document', to='wl_main.LocalDocument'),
        ),
        migrations.AlterField(
            model_name='wildlifelicence',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence_document', to='wl_main.LocalDocument'),
        ),
    ]
