# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 02:55
from __future__ import unicode_literals

from django.db import migrations

def copy_m2m_document_to_local_document(apps, schema_editor):
    CommunicationsLogEntry = apps.get_model('wl_main', 'CommunicationsLogEntry')
    LocalDocument = apps.get_model('wl_main', 'LocalDocument')
    for log_entry in CommunicationsLogEntry.objects.all():
        for document in log_entry.documents.all():   
            local_document = LocalDocument.objects.get(pk=document.pk)
            log_entry.comms_log_documents.add(local_document)

class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0052_auto_20250205_1053'),
    ]

    operations = [
        migrations.RunPython(copy_m2m_document_to_local_document),
    ]
