# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0054_remove_communicationslogentry_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communicationslogentry',
            old_name='comms_log_documents',
            new_name='documents',
        ),
    ]
