# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0055_auto_20250205_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocalDocument',
            new_name='Document',
        ),
    ]
