# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-02-05 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl_main', '0055_auto_20250205_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationslogentry',
            name='staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
